<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>k</string>
	</array>
	<key>name</key>
	<string>LS-DYNA</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.k</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Comments beginning with "$#".</string>
			<key>match</key>
			<string>(\$).*$\n?</string>
			<key>name</key>
			<string>comment.line.double-star.k</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:(((\d+(\.(?=[^a-zA-Z_])\d*)?|(?&lt;=[^0-9a-zA-Z_])\.\d+)(e[\-\+]?\d+)?))J)</string>
			<key>name</key>
			<string>constant.numeric.complex.k</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:(\d+\.\d*(e[\-\+]?\d+)?))(?=[^a-zA-Z_])</string>
			<key>name</key>
			<string>constant.numeric.float.k</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=[^0-9a-zA-Z_])(?i:(\.\d+(e[\-\+]?\d+)?))</string>
			<key>name</key>
			<string>constant.numeric.float.k</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:(\d+e[\-\+]?\d+))</string>
			<key>name</key>
			<string>constant.numeric.float.k</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b([1-9]+[0-9]*|0)</string>
			<key>name</key>
			<string>constant.numeric.integer.decimal.k</string>
		</dict>
		<dict>
			<key>1</key>
			<dict>
				<key>name</key>
				<string>punctuation.definition.string.begin.k</string>
			</dict>
			<key>2</key>
			<dict>
				<key>name</key>
				<string>punctuation.definition.string.end.k</string>
			</dict>
			<key>3</key>
			<dict>
				<key>name</key>
				<string>meta.empty-string.single.k</string>
			</dict>
			<key>match</key>
			<string>(?&lt;!')(')(('))(?!')</string>
			<key>name</key>
			<string>string.quoted.single.single-line.k</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>LS-DYNA keywords preceded by asterisk.</string>
			<key>match</key>
			<string>(\*).*$\n?</string>
			<key>name</key>
			<string>keyword.k</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Catch user defined parameters (such as ELSET names, etc.)</string>
			<key>match</key>
			<string>\w</string>
			<key>name</key>
			<string>string.quoted.single.k</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.k</string>
	<key>uuid</key>
	<string>816b4b30-23b7-4c21-8373-4bad1ae6a531</string>
</dict>
</plist>
